#!/usr/bin/env python3
"""
Tag playlist_manifest.json with genre_primary and genre_secondary.

Run from your Hugo site root:
    python3 tag_genres.py

Reads:  static/playlist_manifest.json
Writes: static/playlist_manifest.json (in place, with backup)

Add new letters to GENRES below as you process them. The script is idempotent —
re-running just refreshes the tags.
"""
import json
import shutil
from pathlib import Path

MANIFEST = Path("static/playlist_manifest.json")

# ---------------------------------------------------------------------------
# Genre map: slug -> (primary, secondary_or_None)
# Slugs match the URL slug your build produces. Keys are lowercased + hyphenated.
# Add letters as you go. The H block is filled in.
# ---------------------------------------------------------------------------
GENRES = {
    # ===== H =====
    "h-e-r":                       ("rnb",        None),
    "haim":                        ("indie",      "pop"),
    "half-pint":                   ("dancehall",  None),
    "halo-benders":                ("indie",      None),
    "hamilton-leithauser":         ("indie",      "rock"),
    "handsome-furs":               ("indie",      "electronic"),
    "hank-ballard-the-midnighters":("rnb",        "rock"),
    "hannah-cohen":                ("indie",      "folk"),
    "harry-nilsson":               ("folk",       "pop"),
    "haru-nemuri":                 ("rock",       None),         # experimental noise/punk lives in rock bucket
    "hatchie":                     ("pop",        "indie"),
    "heart":                       ("rock",       None),
    "heatmiser":                   ("indie",      "rock"),
    "heavenly":                    ("indie",      "pop"),
    "heavy-trash":                 ("rock",       None),
    "hefner":                      ("indie",      "folk"),
    "heidecker-wood":              ("folk",       "rock"),
    "helena-deland":               ("indie",      "folk"),
    "hemlocke-springs":            ("pop",        "indie"),
    "heraldo-negro":               ("electronic", "indie"),
    "herbert":                     ("electronic", None),
    "herman-dune":                 ("folk",       "indie"),
    "hether-3-5-songs":            ("indie",      "pop"),
    "hidden-camera":               ("indie",      None),
    "hilary-duff":                 ("pop",        None),
    "hitkidd":                     ("rap",        None),
    "hives":                       ("rock",       None),
    "hoagy-carmichael":            ("folk",       None),         # american songbook lives nearest folk
    "hold-steady":                 ("indie",      "rock"),
    "hole":                        ("rock",       "indie"),
    "hollies":                     ("rock",       "pop"),
    "homer":                       ("rnb",        None),
    "hoodcelebrityy":              ("dancehall",  "rap"),
    "horsegirl":                   ("indie",      "rock"),
    "hospitality":                 ("indie",      "pop"),
    "hot-boys":                    ("rap",        None),
    "hot-chip":                    ("electronic", "pop"),
    "hovvdy":                      ("indie",      "folk"),
    "how-s-your-news":             ("indie",      None),
    "hunx":                        ("rock",       "pop"),
    "hurray-for-the-riff-raff":    ("indie",      "folk"),
    "hvob":                        ("electronic", None),
    "hyd":                         ("pop",        "electronic"),
    # ===== H 1-offs and covers =====
    "covers-hh":                   ("indie",      None),         # default cover bucket — can re-classify per cover later

    # ===== A =====
    "aaliyah":                     ("rnb",        None),
    "abner-jay":                   ("folk",       None),
    "abra":                        ("rnb",        "electronic"),
    "adan-diaz":                   ("indie",      "pop"),
    "adrianne-lenker":             ("folk",       "indie"),
    "against-me":                  ("rock",       None),
    "al-green":                    ("rnb",        None),
    "alkaline":                    ("dancehall",  None),
    "angel-olsen":                 ("indie",      "folk"),
    "animal-collective":           ("indie",      "electronic"),
    "anohni":                      ("indie",      "electronic"),
    "arcade-fire":                 ("indie",      "rock"),
    "aretha-franklin":             ("rnb",        None),
    "ari-lennox":                  ("rnb",        None),
    "ariana-grande":               ("pop",        "rnb"),
    "asap-rocky":                  ("rap",        None),
    "asher-white":                 ("indie",      None),
    "avey-tare":                   ("indie",      "electronic"),
    "covers-aa":                   ("indie",      None),

    # ===== B =====
    "b-52s":                       ("rock",       "pop"),
    "baby-keem":                   ("rap",        None),
    "banks":                       ("pop",        "rnb"),
    "beach-boys":                  ("pop",        "rock"),
    "beach-house":                 ("indie",      "pop"),
    "beatles":                     ("rock",       "pop"),
    "beatles-3":                   ("rock",       "pop"),
    "beatles-4":                   ("rock",       "pop"),
    "beatles-5":                   ("rock",       "pop"),
    "beck":                        ("indie",      "rock"),
    "beenie-man":                  ("dancehall",  None),
    "beirut":                      ("indie",      "folk"),
    "belle-sebastian":             ("indie",      "folk"),
    "beyonce":                     ("pop",        "rnb"),
    "big-boi":                     ("rap",        None),
    "big-thief":                   ("indie",      "folk"),
    "bill-callahan":               ("folk",       "indie"),
    "billy-bragg":                 ("folk",       None),
    "bjork":                       ("electronic", "pop"),
    "black-keys":                  ("rock",       None),
    "black-lips":                  ("rock",       "indie"),
    "black-mountain":              ("rock",       "indie"),
    "blood-orange":                ("rnb",        "indie"),
    "blow":                        ("indie",      "pop"),
    "bob-dylan":                   ("folk",       "rock"),
    "bob-marley":                  ("dancehall",  None),  # reggae lives in dancehall bucket
    "bonnie-prince-billy":         ("folk",       "indie"),
    "the-boys":                    ("rock",       None),
    "brent-faiyaz":                ("rnb",        "rap"),
    "bright-eyes":                 ("indie",      "folk"),
    "broken-social-scene":         ("indie",      "rock"),
    "bruce-springsteen":           ("rock",       "folk"),
    "bryson-tiller":               ("rnb",        "rap"),
    "built-to-spill":              ("indie",      "rock"),
    "bully":                       ("rock",       "indie"),
    "burna-boy":                   ("rap",        "pop"),  # afrobeats — flag for separate bucket later
    "busy-signal":                 ("dancehall",  None),
    "covers-bb":                   ("indie",      None),

    # ===== C =====
    "cardi-b":                     ("rap",        "pop"),
    "caribou":                     ("electronic", "indie"),
    "carly-rae-jepsen":            ("pop",        None),
    "caroline-polachek":           ("pop",        "indie"),
    "cars":                        ("rock",       "pop"),
    "cat-power":                   ("indie",      "folk"),
    "cat-stevens":                 ("folk",       None),
    "cee-lo-green":                ("rnb",        "rap"),
    "chance-the-rapper":           ("rap",        None),
    "charli-xcx":                  ("pop",        "electronic"),
    "chingy":                      ("rap",        None),
    "christine-and-the-queens":    ("pop",        "indie"),
    "chvrches":                    ("pop",        "electronic"),
    "ciara":                       ("rnb",        "pop"),
    "city-girls":                  ("rap",        None),
    "clairo":                      ("indie",      "pop"),
    "the-clash":                   ("rock",       None),
    "clipse":                      ("rap",        None),
    "coi-leray":                   ("rap",        "pop"),
    "couch-prints":                ("indie",      "pop"),
    "courtney-barnett":            ("indie",      "rock"),
    "covers-cc":                   ("indie",      None),
    "crass":                       ("rock",       None),  # punk
    "creedence-clearwater-revival":("rock",       "folk"),
    "cure":                        ("rock",       None),
    "curtis-mayfield":             ("rnb",        None),

    # ===== D =====
    "covers-dd":                   ("indie",      None),
    "dababy":                      ("rap",        None),
    "daniel-johnston":             ("folk",       "indie"),
    "daryl-hall-john-oates":       ("pop",        "rnb"),
    "david-bowie":                 ("rock",       "pop"),
    "david-vandervelde":           ("indie",      "rock"),
    "dead-moon":                   ("rock",       None),
    "dehd":                        ("indie",      "rock"),
    "demarco":                     ("dancehall",  None),
    "depeche-mode":                ("electronic", "rock"),
    "destiny-s-child":             ("rnb",        "pop"),
    "devendra-banhart":            ("folk",       "indie"),
    "diddy":                       ("rap",        "rnb"),
    "dijon":                       ("rnb",        "indie"),
    "dinah-washington":            ("rnb",        None),
    "ding-dong":                   ("dancehall",  None),
    "dinosaur-jr":                 ("rock",       "indie"),
    "dionne-warwick":              ("rnb",        "pop"),
    "diplo":                       ("electronic", None),
    "dirty-projectors":            ("indie",      None),
    "dixie-chicks":                ("folk",       None),  # country lives in folk bucket
    "dj-khaled":                   ("rap",        None),
    "dmx":                         ("rap",        None),
    "the-do":                      ("indie",      "pop"),
    "doechii":                     ("rap",        "rnb"),
    "doja-cat":                    ("pop",        "rap"),
    "dolly-parton":                ("folk",       None),  # country
    "don-toliver":                 ("rap",        "rnb"),
    "donovan":                     ("folk",       None),
    "doors":                       ("rock",       None),
    "doris":                       ("rnb",        None),
    "dr-dog":                      ("indie",      "rock"),
    "dr-dre":                      ("rap",        None),
    "drake":                       ("rap",        "rnb"),
    "dresden-dolls":                ("rock",      "indie"),
    "drive-by-truckers":           ("rock",       "folk"),
    "duran-duran":                 ("rock",       "pop"),
    "dusty-springfield":           ("pop",        "rnb"),
    "dvsn":                        ("rnb",        None),

    # ===== Number prefixes =====
    "100-gecs":                    ("pop",        "electronic"),  # hyperpop
    "10tik":                       ("dancehall",  None),
    "1975":                        ("indie",      "pop"),
    "2-chainz":                    ("rap",        None),
    "21-savage":                   ("rap",        None),
    "8ball-mjg":                   ("rap",        None),

    # ===== E =====
    "e-40":                        ("rap",        None),
    "earthgang":                   ("rap",        "rnb"),
    "ema":                         ("indie",      "rock"),
    "esg":                         ("rock",       "indie"),  # post-punk
    "est-gee":                     ("rap",        None),
    "edith-piaf":                  ("folk",       None),  # chanson
    "el-perro-del-mar":            ("indie",      "pop"),
    "elastica":                    ("rock",       "indie"),  # britpop
    "eleanor-friedberger":         ("indie",      None),
    "ella-fitzgerald":             ("folk",       None),  # jazz lives in folk
    "elliott-smith":               ("indie",      "folk"),
    "elvis-costello":              ("rock",       "pop"),
    "elvis-presley":               ("rock",       "pop"),
    "eminem":                      ("rap",        None),
    "empath":                      ("rock",       "indie"),
    "empire-of-the-sun":           ("pop",        "electronic"),
    "empress-of":                  ("pop",        "indie"),
    "equipment":                   ("indie",      None),
    "eric-clapton":                ("rock",       None),
    "erika-de-casier":             ("pop",        "rnb"),
    "erykah-badu":                 ("rnb",        None),
    "essex-green":                 ("indie",      "pop"),
    "esther-rose":                 ("folk",       None),
    "etana":                       ("dancehall",  None),
    "ethel-cain":                  ("indie",      "pop"),
    "eurythmics":                  ("pop",        "electronic"),
    "everclear":                   ("rock",       None),
    "everly-brothers":             ("rock",       "folk"),
    "exploding-hearts":            ("rock",       None),  # punk/power-pop
    "ezra-furman":                 ("indie",      "rock"),

    # ===== F =====
    "f-g-s":                       ("indie",      None),
    "f-j-mcmahon":                 ("folk",       None),
    "fidlar":                      ("rock",       "indie"),
    "fka-twigs":                   ("rnb",        "electronic"),
    "fabiana-palladino":           ("pop",        "rnb"),
    "faces":                       ("rock",       None),
    "fannypack":                   ("pop",        "electronic"),
    "father-john-misty":           ("folk",       "indie"),
    "father-philis":               ("dancehall",  None),
    "faye-webster":                ("indie",      "folk"),
    "feist":                       ("indie",      "folk"),
    "felice-brothers":             ("folk",       None),
    "felt":                        ("indie",      None),
    "feng":                        ("dancehall",  None),
    "fever-ray":                   ("electronic", "indie"),
    "fiery-furnaces":              ("indie",      "rock"),
    "fine":                        ("indie",      None),
    "fine-young-cannibals":        ("pop",        "rock"),
    "fiona-apple":                 ("indie",      "folk"),
    "fireboydml":                  ("pop",        "rnb"),  # afrobeats
    "flaming-lips":                ("indie",      "rock"),
    "fleet-foxes":                 ("folk",       "indie"),
    "fleetwood-mac":               ("rock",       None),
    "flo-milli":                   ("rap",        None),
    "florist":                     ("indie",      "folk"),
    "flume":                       ("electronic", None),
    "foo-fighters":                ("rock",       None),
    "forever":                     ("indie",      None),
    "foster-the-people":           ("indie",      "pop"),
    "four-lads":                   ("pop",        None),
    "foushee":                     ("rnb",        "indie"),
    "foxygen":                     ("indie",      "rock"),
    "frances-forever":             ("indie",      "pop"),
    "francis-the-lights":          ("pop",        "indie"),
    "frank-black":                 ("rock",       "indie"),
    "frank-ocean":                 ("rnb",        None),
    "frank-sinatra":               ("pop",        None),
    "frank-zappa":                 ("rock",       None),
    "frankie-cosmos":              ("indie",      "pop"),
    "frankie-valli":               ("pop",        "rnb"),
    "franz-ferdinand":             ("rock",       "indie"),
    "fred-again":                  ("electronic", None),
    "freddie-gibbs":               ("rap",        None),
    "free-range":                  ("indie",      "folk"),
    "french-kicks":                ("indie",      "rock"),
    "french-montana":              ("rap",        None),
    "friends":                     ("indie",      "pop"),
    "frigga":                      ("electronic", None),
    "frightened-rabbit":           ("indie",      "rock"),
    "frog":                        ("indie",      "rock"),
    "front-bottoms":               ("indie",      "rock"),
    "fugees":                      ("rap",        "rnb"),
    "future":                      ("rap",        None),
    "future-bible-heroes":         ("indie",      "pop"),
    "future-islands":              ("indie",      "pop"),
    "futureheads":                 ("rock",       "indie"),
    "covers-ff":                   ("indie",      None),

    # ===== G =====
    "g-flip":                      ("indie",      "pop"),
    "g-perico":                    ("rap",        None),
    "gabriels":                    ("rnb",        "folk"),
    "game":                        ("rap",        None),
    "ganglians":                   ("indie",      "rock"),
    "gangsta-boo":                 ("rap",        None),
    "gappy-ranks":                 ("dancehall",  None),
    "garbage":                     ("rock",       None),
    "gary-numan":                  ("electronic", "rock"),
    "gary-stewart":                ("folk",       None),  # country
    "gaza-kim":                    ("dancehall",  None),
    "gaza-slim":                   ("dancehall",  None),
    "gena-rose-bruce":             ("indie",      None),
    "gene-chandler":               ("rnb",        None),
    "generationals":               ("indie",      "pop"),
    "george-clanton":              ("electronic", "indie"),
    "george-harrison":             ("rock",       None),
    "george-michael":              ("pop",        "rnb"),
    "george-strait":               ("folk",       None),  # country
    "georgia":                     ("electronic", "pop"),
    "gerry-read":                  ("electronic", None),
    "geto-boys":                   ("rap",        None),
    "ghost-mice":                  ("folk",       "indie"),
    "gin-blossoms":                ("rock",       "pop"),
    "ginuwine":                    ("rnb",        None),
    "girl-ray":                    ("indie",      "pop"),
    "girl-talk":                   ("electronic", "rap"),
    "girls":                       ("indie",      "rock"),
    "gladys-knight":               ("rnb",        None),
    "glands":                      ("indie",      "rock"),
    "glass-candy":                 ("electronic", "indie"),
    "glen-campbell":               ("folk",       None),  # country
    "gloss-up":                    ("rap",        None),
    "glume":                       ("indie",      "pop"),
    "gnarls-barkley":              ("rnb",        "rap"),
    "go-team":                     ("indie",      "pop"),
    "gold-youth":                  ("indie",      "pop"),
    "gold-gad":                    ("dancehall",  None),
    "golden-smog":                 ("rock",       "folk"),
    "goldfrapp":                   ("electronic", "pop"),
    "gossip":                      ("rock",       "indie"),
    "govana":                      ("dancehall",  None),
    "grace-ives":                  ("indie",      "pop"),
    "graham-nash":                 ("folk",       "rock"),
    "grave-with-no-name":          ("indie",      None),
    "gravy-train":                 ("electronic", "pop"),
    "green-day":                   ("rock",       None),
    "greenhornes":                 ("rock",       None),
    "grimes":                      ("electronic", "pop"),
    "grizzly-bear":                ("indie",      "folk"),
    "guapdad-4000":                ("rap",        None),
    "gucci-mane":                  ("rap",        None),
    "guided-by-voices":            ("indie",      "rock"),
    "gun-club":                    ("rock",       None),  # punk blues
    "gyptian":                     ("dancehall",  None),
    "covers-gg":                   ("indie",      None),

    # ===== I =====
    "i-octane":                    ("dancehall",  None),
    "idles":                       ("rock",       None),  # post-punk
    "inxs":                        ("rock",       "pop"),
    "ian-sweet":                   ("indie",      None),
    "ibeyi":                       ("rnb",        "folk"),
    "iceage":                      ("rock",       "indie"),
    "icona-pop":                   ("pop",        "electronic"),
    "iggy-pop":                    ("rock",       None),
    "intence":                     ("dancehall",  None),
    "interpol":                    ("rock",       "indie"),
    "ireland-boss":                ("dancehall",  None),
    "iron-wine":                   ("folk",       "indie"),
    "isaiah-rashad":               ("rap",        None),
    "islands":                     ("indie",      None),
    "isley-brothers":              ("rnb",        None),
    "ivor-cutler":                 ("folk",       None),
    "covers-ii":                   ("indie",      None),

    # ===== J =====
    "j-hus":                       ("rap",        None),
    "j-roddy-watson":              ("rock",       "indie"),
    "j-kwon":                      ("rap",        None),
    "j-cole":                      ("rap",        None),
    "j-j-cale":                    ("folk",       "rock"),
    "j-p":                         ("rap",        None),
    "jay-z":                       ("rap",        None),
    "jd-samson":                   ("electronic", "indie"),
    "jeleel":                      ("rap",        None),
    "jems":                        ("indie",      None),
    "jid":                         ("rap",        None),
    "juvenile":                    ("rap",        None),
    "ja-rule":                     ("rap",        None),
    "jack-white":                  ("rock",       "indie"),
    "jackson-5":                   ("rnb",        "pop"),
    "jackson-c-frank":             ("folk",       None),
    "jacquees":                    ("rnb",        None),
    "jada-kingdom":                ("dancehall",  None),
    "jahmiel":                     ("dancehall",  None),
    "jahvillani":                  ("dancehall",  None),
    "jai-paul":                    ("rnb",        "electronic"),
    "jam-city":                    ("electronic", None),
    "james-bobby-purify":          ("rnb",        None),
    "james-blake":                 ("electronic", "rnb"),
    "james-brown":                 ("rnb",        "folk"),  # funk/soul
    "james-carr":                  ("rnb",        None),
    "james-mcmurtry":              ("folk",       "rock"),
    "jamie-xx":                    ("electronic", None),
    "jamila-woods":                ("rnb",        None),
    "janes-addiction":             ("rock",       None),
    "jane-s-addiction":            ("rock",       None),
    "janelle-monae":               ("rnb",        "pop"),
    "janet-jackson":               ("pop",        "rnb"),
    "janis-ian":                   ("folk",       None),
    "japan-man":                   ("indie",      None),
    "japandroids":                 ("rock",       "indie"),
    "japanese-breakfast":          ("indie",      "pop"),
    "jason-isbell":                ("folk",       "rock"),
    "jason-molina":                ("indie",      "folk"),
    "jawbreaker":                  ("rock",       None),  # punk/emo
    "jax-jones":                   ("electronic", "pop"),
    "jay-rock":                    ("rap",        None),
    "jayne-county":                ("rock",       None),  # punk
    "jazmine-sullivan":            ("rnb",        None),
    "jean-dawson":                 ("indie",      "rap"),
    "jeff-buckley":                ("rock",       "folk"),
    "jeff-rosenstock":             ("rock",       "indie"),  # punk
    "jeff-the-brotherhood":        ("rock",       "indie"),
    "jeff-tweedy":                 ("indie",      "folk"),
    "jennifer-lopez":              ("pop",        "rnb"),
    "jenny-lewis":                 ("indie",      "folk"),
    "jens-lekman":                 ("indie",      "pop"),
    "jensen-mcrae":                ("folk",       "indie"),
    "jeremih":                     ("rnb",        None),
    "jeremy-jay":                  ("indie",      None),
    "jermaine-dupri":              ("rap",        "rnb"),
    "jerry-lee-lewis":             ("rock",       None),
    "jess-williamson":             ("folk",       "indie"),
    "jessica-pratt":               ("folk",       "indie"),
    "jessica-ware":                ("pop",        None),
    "jessy-lanza":                 ("electronic", "pop"),
    "jesus-mary-chain":            ("rock",       "indie"),
    "jewel":                       ("folk",       "pop"),
    "jhen-aiko":                   ("rnb",        None),
    "jhene-aiko":                  ("rnb",        None),
    "jidenna":                     ("rnb",        "rap"),
    "jim-e-stack":                 ("electronic", None),
    "jimi-hendrix":                ("rock",       None),
    "jimmy-eat-world":             ("rock",       "indie"),
    "joan-armatrading":            ("folk",       "rnb"),
    "joan-shelley":                ("folk",       None),
    "joanna-sternberg":            ("folk",       None),
    "jockstrap":                   ("indie",      "electronic"),
    "joe-tex":                     ("rnb",        None),
    "joey-purp":                   ("rap",        None),
    "joey-sweeney":                ("indie",      None),
    "john-cale":                   ("rock",       "indie"),
    "john-cooper-clarke":          ("rock",       None),  # punk poet
    "john-denver":                 ("folk",       None),
    "john-lee-hooker":             ("folk",       None),  # blues
    "john-lennon":                 ("rock",       None),
    "john-moods":                  ("indie",      "pop"),
    "john-prine":                  ("folk",       None),
    "johnny-cash":                 ("folk",       "rock"),  # country
    "jonah-yano":                  ("indie",      "folk"),
    "jonathan-richman":            ("rock",       "indie"),
    "jordana":                     ("indie",      "pop"),
    "jorja-smith":                 ("rnb",        None),
    "josephine-foster":            ("folk",       None),
    "joyce-manor":                 ("rock",       "indie"),  # punk/emo
    "juan-waters":                 ("indie",      None),
    "judy-garland":                ("pop",        None),
    "judee-sill":                  ("folk",       None),
    "juiceboxxx":                  ("rap",        "rock"),
    "juicy-j":                     ("rap",        None),
    "julia-jacklin":               ("indie",      "folk"),
    "julia-stone":                 ("folk",       "indie"),
    "julie-byrne":                 ("folk",       None),
    "julio-juramento":              ("folk",      None),
    "jungle":                      ("electronic", "rnb"),
    "junior-boys":                 ("electronic", "indie"),
    "junior-senior":               ("pop",        "electronic"),
    "justice":                     ("electronic", None),
    "justin-bieber":               ("pop",        None),
    "juveniles":                   ("electronic", "pop"),
    "covers-jj":                   ("indie",      None),

    # ===== K =====
    "k-michelle":                  ("rnb",        None),
    "key":                         ("rap",        None),
    "kyle":                        ("rap",        None),
    "kacey-musgraves":             ("folk",       "pop"),  # country
    "kacy-hill":                   ("pop",        "indie"),
    "kali-uchis":                  ("rnb",        "pop"),
    "kamaiyah":                    ("rap",        None),
    "kanye-west":                  ("rap",        None),
    "kapote":                      ("electronic", None),
    "kappa":                       ("dancehall",  None),
    "karl-blau":                   ("folk",       "indie"),
    "kate-bollinger":              ("indie",      "folk"),
    "kate-bush":                   ("pop",        "rock"),
    "kath-bloom":                  ("folk",       None),
    "katy-kirby":                  ("indie",      "folk"),
    "kedr-livanskiy":              ("electronic", "indie"),
    "kehlani":                     ("rnb",        None),
    "kelela":                      ("rnb",        "electronic"),
    "kelis":                       ("rnb",        "pop"),
    "kelley-stoltz":               ("indie",      "rock"),
    "kendrick-lamar":              ("rap",        None),
    "kenny-beats":                 ("rap",        "electronic"),
    "kenny-rogers":                ("folk",       None),  # country
    "keri-hilson":                 ("rnb",        "pop"),
    "kero-kero-bonito":            ("pop",        "electronic"),
    "kevin-abstract":              ("rap",        "indie"),
    "kevin-coyne":                 ("folk",       "rock"),
    "kevin-gates":                 ("rap",        None),
    "kevin-morby":                 ("indie",      "folk"),
    "keyshia-cole":                ("rnb",        None),
    "khalid":                      ("rnb",        "pop"),
    "khruangbin":                  ("indie",      None),
    "kid-creole-and-the-coconuts": ("pop",        "rnb"),
    "kid-cudi":                    ("rap",        None),
    "kid-ink":                     ("rap",        None),
    "killer-mike":                 ("rap",        None),
    "killers":                     ("rock",       "indie"),
    "kills":                       ("rock",       "indie"),
    "kilo-kish":                   ("rap",        "indie"),
    "kim-vincent-fowley":          ("rock",       None),
    "kimya-dawson":                ("folk",       "indie"),
    "king-khan":                   ("rock",       "indie"),
    "king-krule":                  ("indie",      None),
    "king-princess":               ("pop",        "indie"),
    "king-tuff":                   ("rock",       "indie"),
    "kings-of-leon":               ("rock",       None),
    "kinks":                       ("rock",       None),
    "kississippi":                 ("indie",      "rock"),
    "kito":                        ("electronic", "pop"),
    "knife":                       ("electronic", None),
    "koffee":                      ("dancehall",  None),
    "konshens":                    ("dancehall",  None),
    "kraff-gad":                   ("dancehall",  None),
    "krakow-loves-adana":          ("indie",      "electronic"),
    "kranium":                     ("dancehall",  None),
    "kris-kristofferson":          ("folk",       None),  # country
    "kristin-hersh":               ("indie",      "rock"),
    "kurt-cobain":                 ("rock",       None),
    "kurt-vile":                   ("indie",      "rock"),
    "kurtains":                    ("indie",      None),
    "kyla-la-grange":              ("pop",        "indie"),
    "covers-kk":                   ("indie",      None),

    # ===== L =====
    "lcd-soundsystem":             ("electronic", "rock"),
    "ll-cool-j":                   ("rap",        None),
    "lpx":                         ("pop",        "indie"),
    "lucy-cooper-b-handy":         ("indie",      None),
    "lump":                        ("indie",      "electronic"),
    "lvna":                        ("dancehall",  None),
    "la-chat":                     ("rap",        None),
    "la-roux":                     ("pop",        "electronic"),
    "la-sera":                     ("indie",      "rock"),
    "labi-siffre":                 ("folk",       "rnb"),
    "lady":                        ("rnb",        None),
    "lady-gaga":                   ("pop",        None),
    "ladytron":                    ("electronic", "indie"),
    "lakeyah":                     ("rap",        None),
    "lala-lala":                   ("indie",      None),
    "lana-del-rey":                ("pop",        "indie"),
    "latto":                       ("rap",        None),
    "laura-mvula":                 ("rnb",        "pop"),
    "lauryn-hill":                 ("rnb",        "rap"),
    "lavender-diamond":            ("indie",      "folk"),
    "lavish":                      ("dancehall",  None),
    "le-ren":                      ("folk",       None),
    "le-tigre":                    ("rock",       "electronic"),  # punk
    "lead-belly":                  ("folk",       None),  # blues
    "led-zeppelin":                ("rock",       None),
    "lederhosen-lucil":            ("indie",      None),
    "lee-dorsey":                  ("rnb",        None),
    "lee-fields-the-expressions":  ("rnb",        None),
    "left-banke":                  ("rock",       "pop"),
    "lefty-frizzell":              ("folk",       None),  # country
    "leikeli47":                   ("rap",        None),
    "lemonheads":                  ("rock",       "indie"),
    "leon-bridges":                ("rnb",        "folk"),
    "leonard-cohen":               ("folk",       None),
    "les-savy-fav":                ("rock",       "indie"),
    "les-sexareenos":              ("rock",       None),
    "lesley-gore":                 ("pop",        None),
    "let-s-eat-grandma":           ("indie",      "electronic"),
    "leven-kali":                  ("rnb",        None),
    "levi-turner":                 ("indie",      None),
    "lexxus":                      ("dancehall",  None),
    "libertines":                  ("rock",       "indie"),
    "lightning-dust":              ("indie",      "folk"),
    "lights":                      ("pop",        "electronic"),
    "likkle-vybz":                 ("dancehall",  None),
    "lil-baby":                    ("rap",        None),
    "lil-dicky":                   ("rap",        None),
    "lil-keed":                    ("rap",        None),
    "lil-keke":                    ("rap",        None),
    "lil-nas-x":                   ("pop",        "rap"),
    "lil-troy":                    ("rap",        None),
    "lil-wayne":                   ("rap",        None),
    "lil-yachty":                  ("rap",        None),
    "lily-konigsberg":             ("indie",      None),
    "lion-babe":                   ("rnb",        "electronic"),
    "lisa-hype":                   ("dancehall",  None),
    "little-dragon":               ("electronic", "rnb"),
    "little-jerry-williams":       ("rnb",        None),
    "little-richard":              ("rock",       "rnb"),
    "little-wings":                ("indie",      "folk"),
    "liz":                         ("pop",        None),
    "liz-phair":                   ("indie",      "rock"),
    "lizzo":                       ("pop",        "rap"),
    "lo-fi-fnk":                   ("electronic", "pop"),
    "local-h":                     ("rock",       None),
    "lomelda":                     ("indie",      "folk"),
    "lonelady":                    ("indie",      "electronic"),
    "lorde":                       ("pop",        None),
    "loretta-lynn":                ("folk",       None),  # country
    "los-campesinos":              ("indie",      "rock"),
    "lou-reed":                    ("rock",       None),
    "love":                        ("rock",       "folk"),  # 60s psych
    "love-is-all":                 ("indie",      "rock"),
    "love-spells":                 ("indie",      "pop"),
    "love-and-rockets":            ("rock",       "indie"),
    "lovin-spoonful":              ("rock",       "folk"),
    "low":                         ("indie",      "folk"),
    "lowell":                      ("pop",        "indie"),
    "lucinda-williams":            ("folk",       "rock"),  # country
    "ludacris":                    ("rap",        None),
    "luke-kelly":                  ("folk",       None),  # irish
    "luna":                        ("indie",      "rock"),
    "lupe-fiasco":                 ("rap",        None),
    "lutan-fyah":                  ("dancehall",  None),
    "lykke-li":                    ("indie",      "pop"),
    "lyn-collins":                 ("rnb",        None),  # funk
    "lyrii":                       ("dancehall",  None),
    "covers-ll":                   ("indie",      None),

    # ===== M =====
    "m-ward":                      ("folk",       "indie"),
    "m-i-a":                       ("electronic", "pop"),
    "m-o-t-o":                     ("rock",       None),
    "mgmt":                        ("indie",      "electronic"),
    "mia":                         ("electronic", "pop"),
    "mist":                        ("rap",        None),
    "mj-lenderman":                ("indie",      "rock"),
    "mo":                          ("pop",        "electronic"),
    "ms-mr":                       ("indie",      "pop"),
    "muna":                        ("pop",        "indie"),
    "mac-demarco":                 ("indie",      "rock"),
    "madonna":                     ("pop",        None),
    "magdalena-bay":               ("pop",        "electronic"),
    "magnetic-fields":             ("indie",      "pop"),
    "magnolia-electric-co":        ("indie",      "folk"),
    "mahalia-jackson":             ("rnb",        "folk"),  # gospel
    "major-lazer":                 ("electronic", "dancehall"),
    "malice-k":                    ("indie",      "rock"),
    "mallrat":                     ("pop",        "indie"),
    "mamas-the-papas":             ("folk",       "pop"),
    "mandaworld":                  ("dancehall",  None),
    "mando-diao":                  ("rock",       "indie"),
    "mannie-fresh":                ("rap",        None),
    "margo-price":                 ("folk",       "rock"),  # country
    "mariah-carey":                ("pop",        "rnb"),
    "mariah-the-scientist":        ("rnb",        None),
    "marianne-faithfull":          ("rock",       "folk"),
    "marina-allen":                ("folk",       "indie"),
    "mark-kozelek":                ("indie",      "folk"),
    "mark-sultan":                 ("rock",       None),
    "maroon-5":                    ("pop",        None),
    "marvin-gaye":                 ("rnb",        None),
    "mary-j-blige":                ("rnb",        None),
    "mary-jane-girls":             ("rnb",        None),
    "mary-wallopers":              ("folk",       None),  # irish
    "masicka":                     ("dancehall",  None),
    "master-p":                    ("rap",        None),
    "material-issue":              ("rock",       "pop"),  # power-pop
    "matoma":                      ("electronic", "pop"),
    "matt-sweeney-bonnie-prince":  ("folk",       "indie"),
    "matthew-e-white":             ("indie",      "folk"),
    "mavado":                      ("dancehall",  None),
    "maxo-kream":                  ("rap",        None),
    "maytals":                     ("dancehall",  None),
    "mazie":                       ("pop",        "indie"),
    "mazzy-star":                  ("indie",      "rock"),
    "mclusky":                     ("rock",       None),
    "meat-puppets":                ("rock",       "indie"),
    "meek-mill":                   ("rap",        None),
    "meet-me-the-altar":           ("rock",       "indie"),  # punk/emo
    "megan-thee-stallion":         ("rap",        None),
    "megapuss":                    ("indie",      "folk"),
    "melanie":                     ("folk",       None),
    "melody-s-echo-chamber":       ("indie",      "rock"),
    "memories":                    ("indie",      None),
    "memphis-bleek":               ("rap",        None),
    "men-i-trust":                 ("indie",      "pop"),
    "mercury-rev":                 ("indie",      "rock"),
    "merle-haggard":               ("folk",       None),  # country
    "metric":                      ("indie",      "rock"),
    "metro-boomin":                ("rap",        None),
    "michael-hurley":              ("folk",       None),
    "michael-jackson":             ("pop",        "rnb"),
    "michael-leviton":             ("indie",      "folk"),
    "michelle-williams":           ("rnb",        None),
    "migos":                       ("rap",        None),
    "miguel":                      ("rnb",        None),
    "mikal-conin":                 ("indie",      None),
    "mike-jones":                  ("rap",        None),
    "miljon":                      ("indie",      None),
    "miniboone":                   ("indie",      "rock"),
    "ministry":                    ("rock",       "electronic"),  # industrial
    "mirah":                       ("indie",      "folk"),
    "misfits":                     ("rock",       None),  # punk
    "missy-elliott":               ("rap",        "rnb"),
    "mitski":                      ("indie",      "rock"),
    "mixel-pixel":                 ("indie",      "electronic"),
    "miya-folick":                 ("indie",      "pop"),
    "mk-gee":                      ("indie",      "rnb"),
    "modest-mouse":                ("indie",      "rock"),
    "molly-burch":                 ("indie",      "folk"),
    "molly-nilsson":               ("indie",      "electronic"),
    "molly-sarle":                 ("folk",       "indie"),
    "monkees":                     ("rock",       "pop"),
    "monsters-of-folk":            ("folk",       "indie"),
    "montell-fish":                ("rnb",        "indie"),
    "montell-jordan":              ("rnb",        None),
    "mormor":                      ("rnb",        "indie"),
    "morrissey":                   ("rock",       "indie"),
    "mose-allison":                ("folk",       None),  # jazz
    "moses-sumney":                ("indie",      "rnb"),
    "moyann":                      ("dancehall",  None),
    "mr-airplane-man":             ("rock",       None),
    "mr-easy":                     ("dancehall",  None),
    "mr-eazi":                     ("pop",        "rnb"),  # afrobeats
    "mr-twin-sister":              ("indie",      "pop"),
    "mr-vegas":                    ("dancehall",  None),
    "ms-nina":                     ("pop",        "electronic"),
    "ms-roy":                      ("indie",      None),
    "mtume":                       ("rnb",        None),
    "mudra-d-viral":               ("dancehall",  None),
    "mulatu-astatke":              ("folk",       None),  # ethio-jazz
    "mungo-jerry":                 ("rock",       "folk"),
    "mura-masa":                   ("electronic", "pop"),
    "murf-dilly":                  ("rap",        None),
    "mustard":                     ("rap",        None),
    "my-bloody-valentine":         ("rock",       "indie"),  # shoegaze
    "my-idea":                     ("indie",      None),
    "my-morning-jacket":           ("rock",       "indie"),
    "covers-mm":                   ("indie",      None),

    # ===== N =====
    "n-a-s-a":                     ("electronic", "rap"),
    "n-e-r-d":                     ("rap",        "rnb"),
    "nigy-boy":                    ("dancehall",  None),
    "niki":                        ("pop",        "rnb"),
    "nadine-shah":                 ("indie",      "rock"),
    "natalie-bergman":             ("folk",       "indie"),
    "natalie-prass":               ("folk",       "indie"),
    "neeqah":                      ("dancehall",  None),
    "neil-michael-hagerty":        ("rock",       "indie"),
    "neil-young":                  ("folk",       "rock"),
    "nelly":                       ("rap",        None),
    "neneh-cherry":                ("rap",        "pop"),
    "neon-indian":                 ("electronic", "indie"),
    "neutral-milk-hotel":          ("indie",      "folk"),
    "neva-dinova":                 ("indie",      "folk"),
    "new-bomb-turks":              ("rock",       None),  # punk
    "new-christs":                 ("rock",       None),
    "new-edition":                 ("rnb",        "pop"),
    "new-order":                   ("rock",       "electronic"),
    "new-pornographers":           ("indie",      "rock"),
    "nez":                         ("rap",        None),
    "nick-cave":                   ("rock",       "indie"),
    "nick-drake":                  ("folk",       None),
    "nick-gilder":                 ("rock",       "pop"),
    "nick-kroll":                  ("indie",      None),
    "nick-lowe":                   ("rock",       "pop"),
    "nicki-minaj":                 ("rap",        "pop"),
    "nilufer-yanya":               ("indie",      "rock"),
    "nina-simone":                 ("rnb",        "folk"),  # jazz/soul
    "nine-inch-nails":             ("rock",       "electronic"),
    "nipsey-hustle":               ("rap",        None),
    "nirvana":                     ("rock",       None),
    "nite-jewel":                  ("electronic", "pop"),
    "no-doubt":                    ("rock",       "pop"),
    "nocap":                       ("rap",        None),
    "noam-chompsky":               ("indie",      None),
    "normani":                     ("pop",        "rnb"),
    "notnice":                     ("dancehall",  None),
    "notorious-b-i-g":             ("rap",        None),
    "nourished-by-time":           ("rnb",        "electronic"),
    "covers-nn":                   ("indie",      None),

    # ===== O =====
    "o-jays":                      ("rnb",        None),
    "og-ron-c":                    ("rap",        None),
    "oasis":                       ("rock",       "indie"),
    "oblivians":                   ("rock",       None),
    "ocean-colour-scene":          ("rock",       "indie"),
    "odyssey":                     ("rnb",        "pop"),  # disco
    "of-montreal":                 ("indie",      "pop"),
    "offspring":                   ("rock",       None),
    "okkervil-river":              ("indie",      "folk"),
    "oklou":                       ("pop",        "electronic"),
    "ol-dirty-bastard":            ("rap",        None),
    "olivia-rodrigo":              ("pop",        None),
    "one-direction":               ("pop",        None),
    "only-ones":                   ("rock",       None),  # punk
    "orange-juice":                ("indie",      "pop"),
    "orchestral-manoeuvres-in-the-dark": ("electronic", "pop"),
    "origami-angel":               ("rock",       "indie"),
    "orlano-octave":               ("dancehall",  None),
    "otis-redding":                ("rnb",        None),
    "ottilie-wallace":             ("folk",       None),
    "ought":                       ("rock",       "indie"),
    "outkast":                     ("rap",        "rnb"),
    "overmono":                    ("electronic", None),
    "covers-oo":                   ("indie",      None),

    # ===== P =====
    "peel":                        ("indie",      None),
    "pj-harvey":                   ("rock",       "indie"),
    "polica":                      ("indie",      "electronic"),
    "pup":                         ("rock",       "indie"),  # punk
    "palmistry":                   ("electronic", "rnb"),
    "pamputae":                    ("dancehall",  None),
    "panda-bear":                  ("indie",      "electronic"),
    "parenthetical-girls":         ("indie",      "pop"),
    "park-ave":                    ("indie",      "rock"),
    "passion-pit":                 ("indie",      "electronic"),
    "patrick-wolf":                ("indie",      "pop"),
    "patterson-hood":              ("rock",       "folk"),
    "patti-smith":                 ("rock",       None),  # punk
    "paul-mccartney":              ("rock",       "pop"),
    "paul-simon":                  ("folk",       "rock"),
    "paul-westerberg":             ("rock",       "indie"),
    "pavement":                    ("indie",      "rock"),
    "peach-kelli-pop":             ("rock",       "indie"),
    "peaches":                     ("electronic", "rock"),
    "pearl-jam":                   ("rock",       None),
    "pearla":                      ("indie",      "folk"),
    "pecker-dunne":                ("folk",       None),  # irish
    "peggy-gou":                   ("electronic", None),
    "penetrators":                 ("rock",       None),
    "pere-ubu":                    ("rock",       "indie"),
    "perfume-genius":              ("indie",      "pop"),
    "peso-peso":                   ("rap",        None),
    "peter-bjorn-and-john":        ("indie",      "pop"),
    "peter-gabriel":               ("rock",       "pop"),
    "phantogram":                  ("indie",      "electronic"),
    "pharrell-williams":           ("rap",        "rnb"),
    "phoebe-bridgers":             ("indie",      "folk"),
    "phosphorescent":              ("folk",       "indie"),
    "pimp-c":                      ("rap",        None),
    "pinegrove":                   ("indie",      "folk"),
    "pink-floyd":                  ("rock",       None),
    "pink-mountaintops":           ("rock",       "indie"),
    "pinkpantheress":               ("pop",       "electronic"),
    "pipettes":                    ("pop",        "indie"),
    "pixies":                      ("rock",       "indie"),
    "plains":                      ("folk",       "indie"),  # country
    "playboi-carti":               ("rap",        None),
    "playboy-tre":                 ("rap",        None),
    "plies":                       ("rap",        None),
    "pogues":                      ("folk",       "rock"),  # irish punk
    "polyphonic-spree":            ("indie",      "pop"),
    "pom-pom-squad":               ("rock",       "indie"),
    "ponys":                       ("rock",       "indie"),
    "poolside":                    ("electronic", "indie"),
    "popcaan":                     ("dancehall",  None),
    "popeye-ost":                  ("folk",       None),
    "poppy":                       ("rock",       "pop"),
    "porches":                     ("indie",      "pop"),
    "postal-service":              ("indie",      "electronic"),
    "pretenders":                  ("rock",       None),
    "pretti-kitti":                ("dancehall",  None),
    "pretty-girls-make-graves":    ("rock",       "indie"),
    "prince":                      ("rnb",        "pop"),
    "princess-nokia":              ("rap",        None),
    "proclaimers":                 ("rock",       "folk"),
    "professor-murder":            ("indie",      "rock"),
    "project-pat":                 ("rap",        None),
    "psychedellc-furs":             ("rock",      "indie"),
    "psychedelic-furs":            ("rock",       "indie"),
    "pulp":                        ("rock",       "indie"),  # britpop
    "purity-ring":                 ("electronic", "pop"),
    "pusha-t":                     ("rap",        None),
    "covers-pp":                   ("indie",      None),

    # ===== Q =====
    "q":                           ("rnb",        "indie"),
    "q-tip":                       ("rap",        None),
    "quadron":                     ("rnb",        "electronic"),
    "quality-control":             ("rap",        None),
    "quarterbacks":                ("indie",      "rock"),
    "queen":                       ("rock",       None),
    "queens-of-the-stone-age":     ("rock",       None),
    "quintron":                    ("rock",       None),
    "covers-qq":                   ("indie",      None),

    # ===== R =====
    "r-kelly":                     ("rnb",        None),
    "rl-grime":                    ("electronic", None),
    "rosalia":                     ("pop",        "electronic"),
    "raconteurs":                  ("rock",       None),
    "radiohead":                   ("rock",       "indie"),
    "rae-sremmurd":                ("rap",        None),
    "raffi":                       ("folk",       None),
    "rainbow-arabia":              ("indie",      "electronic"),
    "rajahwild":                   ("dancehall",  None),
    "ramones":                     ("rock",       None),  # punk
    "rancid":                      ("rock",       None),  # punk
    "randy-newman":                ("folk",       None),
    "range":                       ("electronic", None),
    "rappin-4-tay":                ("rap",        None),
    "rapture":                     ("rock",       "indie"),
    "rasputina":                   ("rock",       "indie"),
    "ratboys":                     ("indie",      "rock"),
    "raveena":                     ("rnb",        "indie"),
    "raveonettes":                 ("rock",       "indie"),
    "ravyn-lenae":                 ("rnb",        None),
    "ready-for-the-world":         ("rnb",        None),
    "real-mccoy":                  ("electronic", "pop"),
    "red-hot-chili-peppers":       ("rock",       None),
    "red-house-painters":          ("indie",      "folk"),
    "red-rat":                     ("dancehall",  None),
    "redding-hunter":              ("indie",      None),
    "reggie":                      ("rap",        None),
    "reigning-sound":              ("rock",       "indie"),
    "rema":                        ("pop",        "rnb"),  # afrobeats
    "remi-wolf":                   ("pop",        "rnb"),
    "replacements":                ("rock",       "indie"),
    "rhye":                        ("rnb",        "indie"),
    "rich-homie-quan":             ("rap",        None),
    "richard-swift":               ("indie",      "folk"),
    "richard-thompson":            ("folk",       "rock"),
    "richie-kavanagh":             ("folk",       None),  # irish
    "rick-james":                  ("rnb",        "rock"),  # funk
    "rick-ross":                   ("rap",        None),
    "ricky-blaze":                 ("dancehall",  None),
    "ricky-nelson":                ("rock",       "pop"),
    "rihanna":                     ("pop",        "rnb"),
    "rilo-kiley":                  ("indie",      "rock"),
    "rina-sawayama":               ("pop",        None),
    "rita-ora":                    ("pop",        None),
    "ro-james":                    ("rnb",        None),
    "robert-lester-folsom":        ("folk",       None),
    "robyn":                       ("pop",        "electronic"),
    "rocky-votolato":              ("indie",      "folk"),
    "roisin-murphy":               ("electronic", "pop"),
    "roky-erickson":               ("rock",       None),  # psych
    "rolling-stones":              ("rock",       None),
    "romy":                        ("indie",      "electronic"),
    "rostam":                      ("indie",      "pop"),
    "roxy-music":                  ("rock",       "pop"),
    "roy-orbison":                 ("rock",       "pop"),
    "royal-headache":              ("rock",       "indie"),  # punk/pop
    "royksopp":                    ("electronic", None),
    "rudimental":                  ("electronic", "pop"),
    "ryan-adams":                  ("folk",       "rock"),
    "rygin-king":                  ("dancehall",  None),
    "covers-rr":                   ("indie",      None),

    # ===== S =====
    "s":                           ("indie",      None),
    "saint-jhn":                   ("rap",        "rnb"),
    "sasami":                      ("indie",      "rock"),
    "sault":                       ("rnb",        None),
    "school-official":             ("indie",      None),
    "sg-lewis":                    ("electronic", "pop"),
    "soak":                        ("indie",      "folk"),
    "sophie":                      ("electronic", "pop"),
    "strfkr":                      ("indie",      "electronic"),
    "sza":                         ("rnb",        None),
    "sabrina-carpenter":           ("pop",        None),
    "sade":                        ("rnb",        None),
    "safe-mind":                   ("indie",      None),
    "sahara-hotnights":            ("rock",       "indie"),
    "saint-etienne":               ("pop",        "electronic"),
    "saintseneca":                 ("indie",      "folk"),
    "sam-dave":                    ("rnb",        None),
    "sam-burton":                  ("folk",       None),
    "sam-cooke":                   ("rnb",        None),
    "samantha-sang":               ("pop",        None),
    "samantha-urbani":             ("indie",      "pop"),
    "samia":                       ("indie",      "folk"),
    "sandro-perri":                ("indie",      "electronic"),
    "santigold":                   ("indie",      "electronic"),
    "sasha-siem":                  ("indie",      "folk"),
    "sasha-sloan":                 ("pop",        None),
    "saturday-looks-good-to-me":   ("indie",      None),
    "saweetie":                    ("rap",        None),
    "schoolboy-q":                 ("rap",        None),
    "scorpions":                   ("rock",       None),
    "sean-paul":                   ("dancehall",  None),
    "secret-machines":             ("rock",       "indie"),
    "seinabo-sey":                 ("pop",        "rnb"),
    "selena-gomez":                ("pop",        None),
    "serengeti":                   ("rap",        "indie"),
    "sevyn-streeter":              ("rnb",        None),
    "sexxy-red":                   ("rap",        None),
    "shakira":                     ("pop",        None),
    "shane-e":                     ("dancehall",  None),
    "shane-o":                     ("dancehall",  None),
    "shangri-las":                 ("pop",        "rock"),
    "shannon-lay":                 ("folk",       "indie"),
    "sharon-jones":                ("rnb",        None),
    "sharon-van-etten":            ("indie",      "folk"),
    "shatta-wale":                 ("dancehall",  "pop"),  # afro-dancehall
    "shawn-storm":                 ("dancehall",  None),
    "sheer-mag":                   ("rock",       None),
    "shelly-thunder":              ("dancehall",  None),
    "shenseea":                    ("dancehall",  None),
    "sheryl-crow":                 ("rock",       "pop"),
    "shins":                       ("indie",      "pop"),
    "shocked-minds":               ("rock",       "indie"),
    "shootergang-kony":            ("rap",        None),
    "shout-out-louds":             ("indie",      "pop"),
    "shygirl":                     ("electronic", "pop"),
    "sibylle-baier":               ("folk",       None),
    "sidekicks":                   ("rock",       "indie"),  # punk
    "siliver-jews":                ("indie",      "folk"),
    "silver-jews":                 ("indie",      "folk"),
    "simon-garfunkel":             ("folk",       None),
    "sister-sledge":               ("rnb",        "pop"),  # disco
    "sizzla":                      ("dancehall",  None),
    "sky-ferreira":                ("pop",        "indie"),
    "slapp-happy":                 ("indie",      None),
    "sleater-kinney":              ("rock",       "indie"),
    "sleigh-bells":                ("indie",      "rock"),
    "slick-rick":                  ("rap",        None),
    "slits":                       ("rock",       None),  # punk
    "slothrust":                   ("rock",       "indie"),
    "sly-the-family-stone":        ("rnb",        "rock"),  # funk
    "smashing-pumpkins":           ("rock",       None),
    "smerz":                       ("electronic", "pop"),
    "smino":                       ("rap",        "rnb"),
    "smiths":                      ("rock",       "indie"),
    "smog":                        ("indie",      "folk"),
    "smoosh":                      ("indie",      "pop"),
    "snail-mail":                  ("indie",      None),
    "snakehips":                   ("electronic", "pop"),
    "sneaker-pimps":               ("electronic", "rock"),  # trip-hop
    "snoh-aalegra":                ("rnb",        None),
    "snoop-dogg":                  ("rap",        None),
    "snowsa":                      ("rap",        "rnb"),
    "soccer-mommy":                ("indie",      "rock"),
    "sofia-royer":                 ("indie",      "pop"),
    "solange":                     ("rnb",        None),
    "son-house":                   ("folk",       None),  # blues
    "son-ambulance":               ("indie",      None),
    "songs-ohia":                  ("indie",      "folk"),
    "sonic-youth":                 ("rock",       "indie"),
    "sorry-girls":                 ("indie",      "pop"),
    "soundgarden":                 ("rock",       None),
    "spank-rock":                  ("rap",        "electronic"),
    "sparklehorse":                ("indie",      "rock"),
    "sparks":                      ("rock",       "pop"),
    "special-interest":            ("rock",       None),  # punk
    "spice":                       ("dancehall",  None),
    "spice-girls":                 ("pop",        None),
    "spinners":                    ("rnb",        None),
    "spoon":                       ("indie",      "rock"),
    "squash":                      ("dancehall",  None),
    "squeeze":                     ("rock",       "pop"),
    "ssion":                       ("indie",      "electronic"),
    "st-vincent":                  ("indie",      "rock"),
    "star-moles":                  ("indie",      None),
    "starface":                    ("dancehall",  None),
    "stephen-malkmus":             ("indie",      "rock"),
    "steve-lacy":                  ("rnb",        "indie"),
    "stevie-wonder":               ("rnb",        None),
    "strand-of-oaks":              ("indie",      "rock"),
    "strange-conversations":       ("indie",      None),
    "strokes":                     ("rock",       "indie"),
    "sublime":                     ("rock",       None),
    "sufjan-stevens":              ("indie",      "folk"),
    "suga-free":                   ("rap",        None),
    "sugarbabes":                  ("pop",        "rnb"),
    "sugarcubes":                  ("indie",      "rock"),
    "suicide":                     ("rock",       "electronic"),  # punk synth
    "suki-waterhouse":             ("indie",      "pop"),
    "summer-walker":               ("rnb",        None),
    "sun-june":                    ("indie",      "folk"),
    "sun-kill-moon":               ("indie",      "folk"),
    "sunday-service-choir":        ("rnb",        None),  # gospel
    "super-cat":                   ("dancehall",  None),
    "super-wild-horses":           ("rock",       "indie"),
    "superdrag":                   ("rock",       "indie"),
    "supergrass":                  ("rock",       "indie"),  # britpop
    "superviolet":                 ("indie",      "rock"),
    "supremes":                    ("rnb",        "pop"),
    "swamp-dogg":                  ("rnb",        "folk"),
    "sweatheart":                  ("indie",      None),
    "syd":                         ("rnb",        None),
    "sylvan-esso":                 ("indie",      "electronic"),
    "covers-ss":                   ("indie",      None),

    # ===== T =====
    "t-rex":                       ("rock",       None),
    "t-i":                         ("rap",        None),
    "tlc":                         ("rnb",        "pop"),
    "tops":                        ("indie",      "pop"),
    "tv-girl":                     ("indie",      "pop"),
    "tv-on-the-radio":             ("indie",      "rock"),
    "takeova":                     ("dancehall",  None),
    "taken-by-trees":              ("indie",      "folk"),
    "talking-heads":               ("rock",       None),
    "tame-impala":                 ("indie",      "rock"),
    "taxidermists":                ("indie",      None),
    "taylor-swift":                ("pop",        "folk"),
    "taylor-vick":                 ("indie",      "folk"),
    "team-rilla":                  ("dancehall",  None),
    "tears-for-fears":             ("pop",        "rock"),
    "ted-leo":                     ("rock",       "indie"),  # punk
    "ted-lucas":                   ("folk",       None),
    "teejay":                      ("dancehall",  None),
    "teezo-touchdown":             ("rap",        "rnb"),
    "tegan-and-sara":              ("indie",      "pop"),
    "tei-shi":                     ("pop",        "indie"),
    "television":                  ("rock",       None),  # punk
    "tenanacious-d":                ("rock",      None),
    "tenacious-d":                 ("rock",       None),
    "tennis":                      ("indie",      "pop"),
    "tenor-saw":                   ("dancehall",  None),
    "teyana-taylor":               ("rnb",        None),
    "the-9ine":                    ("dancehall",  None),
    "the-faint":                   ("indie",      "electronic"),
    "the-go":                      ("rock",       None),
    "the-king-is-gone-so-are-you": ("indie",      None),
    "the-men":                     ("rock",       "indie"),
    "the-national":                ("indie",      "rock"),
    "the-organ":                   ("indie",      "rock"),
    "the-school":                  ("indie",      "pop"),
    "the-tallest-man-on-earth":    ("folk",       "indie"),
    "the-the":                     ("rock",       "indie"),
    "the-time":                    ("rnb",        None),  # funk
    "the-dream":                   ("rnb",        None),
    "thermals":                    ("rock",       "indie"),  # punk
    "thin-lizzy":                  ("rock",       None),
    "this-is-lorelei":             ("indie",      "folk"),
    "three-6-mafia":               ("rap",        None),
    "three-queens-in-mourning":    ("folk",       "indie"),
    "throwing-muses":              ("rock",       "indie"),
    "thundercat":                  ("rnb",        "electronic"),
    "tierra-whack":                ("rap",        None),
    "tifa":                        ("dancehall",  None),
    "tigercats":                   ("indie",      "pop"),
    "tilly-the-wall":              ("indie",      "folk"),
    "tim-hardin":                  ("folk",       None),
    "tim-heidecker":               ("indie",      "folk"),
    "tim-and-eric":                ("indie",      None),
    "timbaland":                   ("rap",        "rnb"),
    "times-new-viking":            ("indie",      "rock"),
    "tina-turner":                 ("rnb",        "rock"),
    "tinashe":                     ("rnb",        "pop"),
    "tink":                        ("rnb",        "rap"),
    "tirzah":                      ("electronic", "rnb"),
    "titus-andronicus":            ("rock",       "indie"),  # punk
    "tkay-maidza":                 ("rap",        "pop"),
    "toadies":                     ("rock",       None),
    "todd-rundgren":               ("rock",       "pop"),
    "tokischa":                    ("rap",        "pop"),  # reggaeton
    "tom-petty":                   ("rock",       None),
    "tom-t-hall":                  ("folk",       None),  # country
    "tom-waits":                   ("folk",       "rock"),
    "tomberlin":                   ("indie",      "folk"),
    "tommy-james-the-shondells":   ("rock",       "pop"),
    "tommy-lee-sparta":            ("dancehall",  None),
    "tommy-richman":               ("rnb",        "pop"),
    "tommy-roe":                   ("pop",        "rock"),
    "too-short":                   ("rap",        None),
    "tori-amos":                   ("rock",       "pop"),
    "toro-y-moi":                  ("indie",      "electronic"),
    "tory-lanez":                  ("rnb",        "rap"),
    "toto":                        ("rock",       "pop"),
    "tough-alliance":              ("indie",      "pop"),
    "tracy-the-plastics":          ("indie",      "electronic"),
    "trembling-bells-bonnie-prince-billy": ("folk", "indie"),
    "trey-songz":                  ("rnb",        None),
    "trick-daddy":                 ("rap",        None),
    "trina":                       ("rap",        None),
    "troggs":                      ("rock",       None),
    "turnstile":                   ("rock",       None),  # hardcore
    "ty-dolla-sign":               ("rnb",        "rap"),
    "ty-segall":                   ("rock",       "indie"),
    "tyla-yaweh":                  ("rap",        None),
    "tyler-childers":              ("folk",       None),  # country
    "tyler-the-creator":           ("rap",        None),
    "covers-tt":                   ("indie",      None),

    # ===== U =====
    "u-s-girls":                   ("indie",      "pop"),
    "u2":                          ("rock",       None),
    "ugk":                         ("rap",        None),
    "uniqu3":                      ("electronic", None),
    "uffie":                       ("electronic", "pop"),
    "uncle-tupelo":                ("rock",       "folk"),  # alt-country
    "undertones":                  ("rock",       None),  # punk
    "unicorns":                    ("indie",      "rock"),
    "united-state-of-electronica": ("electronic", "indie"),
    "unknown-mortal-orchestra":    ("indie",      "rock"),
    "usher":                       ("rnb",        "pop"),
    "covers-uu":                   ("indie",      None),

    # ===== V =====
    "va-g-spots":                  ("electronic", None),
    "vacationer":                  ("indie",      "pop"),
    "vagabon":                     ("indie",      "folk"),
    "valee":                       ("rap",        None),
    "valiant":                     ("dancehall",  None),
    "vampire-weekend":             ("indie",      "pop"),
    "van-morrison":                ("rock",       "folk"),
    "vanessa-bling":               ("dancehall",  None),
    "vaselines":                   ("indie",      "rock"),
    "vashti-bunyan":               ("folk",       None),
    "vegyn":                       ("electronic", None),
    "velvet-underground":          ("rock",       None),
    "vershon":                     ("dancehall",  None),
    "vetiver":                     ("folk",       "indie"),
    "viagra-boys":                 ("rock",       None),  # post-punk
    "vic-mensa":                   ("rap",        None),
    "victoria-mont":               ("indie",      "pop"),
    "vince-staples":               ("rap",        None),
    "vines":                       ("rock",       "indie"),
    "violent-femmes":              ("rock",       "folk"),
    "voidz":                       ("rock",       "indie"),
    "voxtrot":                     ("indie",      "pop"),
    "covers-vv":                   ("indie",      None),

    # ===== W =====
    "westside-boogie":             ("rap",        None),
    "wale":                        ("rap",        None),
    "walkmen":                     ("indie",      "rock"),
    "wallows":                     ("indie",      "pop"),
    "walter-meego":                ("electronic", "indie"),
    "war-on-drugs":                ("indie",      "rock"),
    "warren-zevon":                ("rock",       "folk"),
    "warriors-ost-2024":           ("indie",      None),
    "water-from-your-eyes":        ("indie",      "rock"),
    "waxahatchee":                 ("indie",      "folk"),
    "weather-station":             ("folk",       "indie"),
    "wednesday":                   ("indie",      "rock"),
    "weeknd":                      ("rnb",        "pop"),
    "ween":                        ("rock",       "indie"),
    "weezer":                      ("rock",       "indie"),
    "weird-al":                    ("pop",        "rock"),
    "wesley-bright":               ("rnb",        None),
    "westerman":                   ("indie",      "folk"),
    "wet":                         ("indie",      "pop"),
    "wet-leg":                     ("indie",      "rock"),
    "weyes-blood":                 ("indie",      "folk"),
    "when-saints-go-machine":      ("indie",      "electronic"),
    "white-magic":                 ("indie",      "folk"),
    "white-reaper":                ("rock",       None),
    "white-stripes":               ("rock",       "indie"),
    "white-williams":              ("indie",      "electronic"),
    "white-wires":                 ("rock",       "indie"),
    "whitney":                     ("indie",      "folk"),
    "whitney-houston":             ("pop",        "rnb"),
    "who":                         ("rock",       None),
    "widowspeak":                  ("indie",      "folk"),
    "wilco":                       ("indie",      "folk"),
    "wild-nothing":                ("indie",      "pop"),
    "wiley":                       ("rap",        "electronic"),  # grime
    "wilfy-d":                     ("dancehall",  None),
    "william-bell":                ("rnb",        None),
    "willie-cobbs":                ("folk",       None),  # blues
    "willie-nelson":               ("folk",       None),  # country
    "wilson-pickett":              ("rnb",        None),
    "wimple-winch":                ("rock",       None),
    "wings":                       ("rock",       "pop"),
    "winter":                      ("indie",      "pop"),
    "winter-s-bone":               ("folk",       None),
    "wipers":                      ("rock",       None),  # punk
    "wire":                        ("rock",       None),  # post-punk
    "wise-blood":                  ("indie",      "electronic"),
    "witch":                       ("rock",       None),
    "wiz-khalifa":                 ("rap",        None),
    "wizkid":                      ("pop",        "rnb"),  # afrobeats
    "wolf-parade":                 ("indie",      "rock"),
    "wooden-wand":                 ("folk",       "indie"),
    "woods":                       ("indie",      "folk"),
    "wreckless-eric":              ("rock",       None),  # punk
    "covers-ww":                   ("indie",      None),

    # ===== X =====
    "xtc":                         ("rock",       "pop"),
    "xxxtentacion":                ("rap",        "rnb"),
    "xxxtentacion-clean":          ("rap",        "rnb"),
    "xiu-xiu":                     ("indie",      "electronic"),
    "covers-xx":                   ("indie",      None),

    # ===== Y =====
    "y":                           ("rap",        None),
    "yacht":                       ("indie",      "electronic"),
    "yg":                          ("rap",        None),
    "yaeji":                       ("electronic", "pop"),
    "yeah-yeah-yeahs":             ("rock",       "indie"),
    "yeasayer":                    ("indie",      "electronic"),
    "yellowman":                   ("dancehall",  None),
    "yo-gotti":                    ("rap",        None),
    "yo-la-tengo":                 ("indie",      "rock"),
    "yoko-ono":                    ("rock",       "indie"),
    "young-ejecta":                ("electronic", "indie"),
    "young-fathers":               ("indie",      "rap"),
    "young-gun-silver-fox":        ("pop",        "rock"),
    "young-thug":                  ("rap",        None),
    "youngboy-never-broke-again":  ("rap",        None),
    "youth-lagoon":                ("indie",      "electronic"),
    "yumi-zouma":                  ("indie",      "pop"),
    "yung-bae":                    ("electronic", "pop"),
    "yuno":                        ("indie",      "rnb"),
    "yves-tumor":                  ("indie",      "rock"),
    "covers-yy":                   ("indie",      None),

    # ===== Z =====
    "z-ro":                        ("rap",        None),
    "zacari":                      ("rnb",        "rap"),
    "zach-bryan-40-watt-isbell":   ("folk",       None),
    "zach-bryan-honktonk":         ("folk",       None),
    "zach-bryan-live":             ("folk",       None),
    "zach-bryan-love-lay-in-bed-24hrs": ("folk", None),
    "zach-bryan-middle-road-troubadour": ("folk", None),
    "zach-bryan-porch-rock":       ("folk",       None),
    "zach-bryan-wisdom":           ("folk",       None),
    "zach-bryan-ballads":          ("folk",       None),
    "zach-bryan-bed-rock":         ("folk",       None),
    "zach-bryan-and-the-best-only-girl": ("folk", None),
    "zach-bryan-favorites-from-with-heaven-on-top": ("folk", None),
    "zach-vehicle":                ("folk",       None),
    "zagga":                       ("dancehall",  None),
    "ziggens":                     ("rock",       None),
    "zipper":                      ("rock",       None),
    "zola-jesus":                  ("indie",      "electronic"),
    "zombies":                     ("rock",       "pop"),
    "covers-zz":                   ("indie",      None),

    # ===== Lowercase oddities =====
    "jlo":                         ("pop",        "rnb"),

    # ===== # / number 1-off buckets — letter slugs =====
    # These will be tagged via fallback if needed; primary 1-off buckets per letter use slug like "a-2020s-1offs"
}


def slug_of(record):
    """Match the slug logic in the index template's buildHref()."""
    kind = record.get("kind")
    letter = (record.get("letter") or "#").lower()
    era = (record.get("era") or "").lower()
    if kind == "1off_bucket":
        if era in ("dh", "dancehall"):
            era = "dh"
        return f"{letter}-{era}-1offs"
    if kind == "cover":
        return f"covers-{letter}{letter}"
    # artist — strip suffixes the way the template does, then slugify
    name = (record.get("name") or "").strip()
    import re
    s = name
    s = re.sub(r"\s*[-\u2013\u2014]\s*(XX+|\d+\+?)\s*(Songs?|Remixes?|IP\s*Songs?|DH\s*Songs?|Rap\s*Songs?|Top\s*Songs?|Sons|Sogs)\s*$", "", s, flags=re.I)
    s = re.sub(r"\s*[-\u2013\u2014]\s*DH\s*SONGS?\s*$", "", s, flags=re.I)
    s = re.sub(r"\s*[-\u2013\u2014]\s*Top\s*Songs?\s*$", "", s, flags=re.I)
    s = re.sub(r"\s*[-\u2013\u2014]\s*Best\s*Song\s*$", "", s, flags=re.I)
    s = re.sub(r"\s*[-\u2013\u2014]\s*Covers?\s*$", "", s, flags=re.I)
    s = re.sub(r"\s*[-\u2013\u2014]\s*INSTRUMENTAL\s*Songs?\s*$", "", s, flags=re.I)
    s = re.sub(r"\s*[-\u2013\u2014]\s*IRISH\s*Songs?\s*$", "", s, flags=re.I)
    s = re.sub(r"\s*[-\u2013\u2014]\s*[\w\s]+\s*Songs?\s*$", "", s, flags=re.I)
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()
    return s


def main():
    if not MANIFEST.exists():
        raise SystemExit(f"Manifest not found: {MANIFEST.resolve()}")
    backup = MANIFEST.with_suffix(".json.bak")
    shutil.copy(MANIFEST, backup)
    print(f"Backup: {backup}")

    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise SystemExit("Expected manifest to be a JSON list.")

    tagged = 0
    untagged_by_letter = {}
    processed_letters = set()
    for s in GENRES:
        # Pull the first letter from the slug, treating "covers-xx" specially
        if s.startswith("covers-") and len(s) >= 9:
            processed_letters.add(s[7].upper())
        else:
            processed_letters.add(s[0].upper())

    for r in data:
        if r.get("kind") not in ("artist", "1off_bucket", "cover"):
            continue
        s = slug_of(r)
        if s in GENRES:
            primary, secondary = GENRES[s]
            r["genre_primary"] = primary
            if secondary:
                r["genre_secondary"] = secondary
            else:
                r.pop("genre_secondary", None)
            tagged += 1
        else:
            letter = (r.get("letter") or "#").upper()
            if letter in processed_letters:
                untagged_by_letter.setdefault(letter, []).append((s, r.get("name")))

    MANIFEST.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Tagged: {tagged}")
    if untagged_by_letter:
        print(f"\nUntagged records in processed letters ({sum(len(v) for v in untagged_by_letter.values())}):")
        for letter in sorted(untagged_by_letter):
            print(f"\n  [{letter}]")
            for s, n in untagged_by_letter[letter]:
                print(f"    {s:40s}  {n}")


if __name__ == "__main__":
    main()